Refactor CI workflow and SSH playbooks for key handling and cleanup.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -84,28 +84,28 @@ jobs:
           APP_AUTH_TOKEN: ${{ secrets.APP_AUTH_TOKEN }}
         run: |
           SCRIPT="
-          set -e
+            set -e
 
-          # Start by removing existing work directory in the remote server
-          rm -rf $WORK_DIR
+            # Start by removing existing work directory in the remote server
+            rm -rf $WORK_DIR
 
-          # Clone the repo in the remote server
-          git clone https://$GH_TOKEN@github.com/$GH_REPO.git $WORK_DIR
+            # Clone the repo in the remote server
+            git clone https://$GH_TOKEN@github.com/$GH_REPO.git $WORK_DIR
 
-          # Go to the directory where the docker-compose.yml lives
-          cd $WORK_DIR/app
+            # Go to the directory where the docker-compose.yml lives
+            cd $WORK_DIR/app
 
-          # Wind everything down and clean up all the containers associated with this file
-          docker compose down --rmi all --volumes --remove-orphans || true
+            # Wind everything down and clean up all the containers associated with this file
+            docker compose down --rmi all --volumes --remove-orphans || true
 
-          # Sometimes images don't go away
-          docker rmi -f $(docker compose images -q) || true
+            # Sometimes images don't go away
+            docker rmi -f $(docker compose images -q) || true
 
-          # Export environment variables
-          export AUTH_TOKEN=$APP_AUTH_TOKEN
+            # Export environment variables
+            export AUTH_TOKEN=$
 
-          # Spin up the containers with the environment variable from the .env file
-          docker compose up -d --build
+            # Spin up the containers with the environment variable from the .env file
+            docker compose up -d --build
           "
 
           # Run on the remote machine
